### ISSUE TITLE
"Rachel Fredericks" is not able to look up her name using the tool

### ISSUE THREAD

**Issue by rojasalexandra** [BrandNewCongress/candidate-evaluator#8] opened 2017-03-10 18:26 UTC
Looks to be all set up in Airtable correctly, but she has been unable to find herself to start making evaluations. This has been happening since yesterday evening (3/9 7 pm MT).

**Comment by judieschu** [comment] 2017-03-10 21:16
This is resolved.

**Comment by ben-pr-p** [comment] 2017-03-10 22:19
Closing for now since it can't be reproduced

**Closed as completed by ben-pr-p** 2017-03-10 22:19 UTC
